[network]
name = "mainnet"
rpc_url = "https://mainnet-rich-indexer.ckbapp.dev"

[contracts]
stealth_lock_code_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
ct_token_code_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
ct_info_code_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
ckb_auth_code_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"

[cell_deps.ckb_auth]
tx_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
index = 0
data_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"

[cell_deps.stealth_lock]
tx_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
index = 1
data_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
type_id_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"

[cell_deps.ct_info]
tx_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
index = 0
data_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
type_id_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"

[cell_deps.ct_token]
tx_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
index = 0
data_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
type_id_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
