[network]
name = "testnet"
rpc_url = "https://testnet.ckbapp.dev"
# Start scanning from block after contract deployment to skip irrelevant history
scan_start_block = 20117508

[contracts]
stealth_lock_code_hash = "0x0dc965b5bfb6db2759275ad7d92ee502e10955cca789d001af03e3576cfe3f1c"
ct_token_code_hash = "0x708185bddbd4b22b456449235c230f74e85a26aaa720ec3eb1299843300ff34a"
ct_info_code_hash = "0x150fdb31620455e6b2a1c2bdb44fa3b97474aedf0480c3acf8558d90e9ae156b"
ckb_auth_code_hash = "0x0915983bb31584df4566e0946fd00ef1e9a75ad37a39ce70fec9b5cbf3b87021"

[cell_deps.ckb_auth]
tx_hash = "0xa0e99b29fd154385815142b76668d5f4ecf30ae85bc2942bd21e9e51b9066f97"
index = 0

[cell_deps.stealth_lock]
tx_hash = "0x305a174d8af95368aac1768bf7b1fe7398a6cb6b04808fbbc685300403318428"
index = 0

[cell_deps.ct_info]
tx_hash = "0x305a174d8af95368aac1768bf7b1fe7398a6cb6b04808fbbc685300403318428"
index = 1

[cell_deps.ct_token]
tx_hash = "0x305a174d8af95368aac1768bf7b1fe7398a6cb6b04808fbbc685300403318428"
index = 2
